port: 5000
auth_realm: "klouds"
user_namespace: "user:"
token_namespace: "token:"
redis_server: "markdown-redis:6379"
redis_password: ""
hmac_key: "someSaltySalts"
mysql_connection_string: "root@(markdown-mysql:3306)/markdown-mysql?charset=utf8&parseTime=True"
