module.exports = {
  API_URL       : 'http://localhost:5000',
  AUTH_DATA_KEY : 'authData',
  ACTIONS       : {
    SET_VIEW         : 'set_view',
    SET_ROUTE        : 'set_route',
    LOGIN            : 'login',
    LOGOUT           : 'logout',
    REGISTER           : 'register',
    SYNC_DOCUMENTS   : 'sync_documents',
    CREATE_DOCUMENT  : 'create_document',
    SAVE_DOCUMENT  : 'save_document',
    REMOVE_DOCUMENT  : 'remove_document',
    SELECT_DOCUMENT  : 'select_document',
    ARCHIVE_DOCUMENT : 'archive_document',
    OPEN_IMPORT : 'open_import',
    PREVIEW_DOCUMENT : 'preview_document',
    FULLSCREEN_DOCUMENT  : 'fullscreen_document ',
  },
};
